spring.application.name=mis-libros-her

spring.datasource.url=jdbc:mariadb://localhost:3306/libros_her
spring.datasource.username=rex
spring.datasource.password=morningstar
#spring.datasource.url=${URL_MARIADB}
#spring.datasource.username=${USR_MARIADB}
#spring.datasource.password=${PWD_MARIADB}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
